version: '3.8'
services:
  pep-app:
    build: .
    ports:
      - "8501:8501"
    shm_size: '2gb' # Very important for PyTorch/Numpy 3D data
    deploy:
      resources:
        limits:
          memory: 4G # Minimum 4GB for 3D processing
    volumes:
      - .:/app
